In [1]:
%cd /Users/trancatkhanh/Downloads/GAME

/Users/trancatkhanh/Downloads/GAME


In [2]:
import numpy as np
from base.Splendor_v3.env import *
#0 Array bias trong mỗi trận
#1 Array bias sau 100k trận 
#2 Lưu số trận 
#3 lưu hệ số đã dùng 
#4 Tỷ lệ thắng khi đấu 10k trận 
#5 Trigger để train 100k trận 
#6 Đếm số lần yếu liên tiếp
#7 
#8 State của trận đấu
#9 Action của trận đấu
#10 Reward của trận đấu
#11 Số trận lưu state
#12 Số trận thắng của hệ số mới 

perx = [np.array([np.random.rand(getActionSize()) for _ in range(1)]),np.zeros((1,getActionSize())),np.zeros((1,1)),np.array([np.random.rand(getActionSize()) for _ in range(1)]),np.zeros((1,2)),np.zeros((1,2)),np.zeros((1,1)),np.zeros((1,1)),np.zeros((200000,getStateSize())),np.zeros((200000,1)),np.zeros((200000,1)),np.zeros((1,1))]
                         #0                                                      #1                   #2              #3                                                            #4              #5               #6                #7               #8                                   #9               #10                       #11         

In [3]:
perx

[array([[0.46565798, 0.43019202, 0.77290667, 0.1054475 , 0.89403002,
         0.59275237, 0.19574387, 0.69384178, 0.89676086, 0.28980145,
         0.32077255, 0.72484483, 0.85912162, 0.32395284, 0.99938509]]),
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[0.]]),
 array([[7.12825172e-01, 3.80164000e-01, 6.62635458e-01, 4.54548781e-01,
         6.89604174e-01, 4.61635081e-01, 5.21536155e-01, 4.07377428e-01,
         1.99027509e-01, 2.64327960e-01, 5.04408378e-01, 6.85633453e-01,
         3.77467723e-04, 9.24165413e-01, 4.31522728e-01]]),
 array([[0., 0.]]),
 array([[0., 0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 ar

In [8]:
@njit()
def p_bias(state,per):
    # Chuyển Mode gồm 3 mode mode 0 - train , mode 1 - test , mode 2 - train policy yếu ,mode 3 - test policy yếu,mode 4 - lưu state
    if per[4][0][0] > per[5][0][1] and per[4][0][1] == 1000:
      per[3][0] = np.copy(per[1][0]/np.max(per[1][0]))
      # Lưu lại kết quả thắng
      per[5][0][1] = 0 
      per[5][0][1] += (per[4][0][0])
      # Rest số trận thắng và số trận đấu 
      per[4][0][0] = 0
      per[4][0][1] = 0 
      # Chuyển sang train
      per[5][0][0] = 0 
      per[2][0][0] = 0
      per[1][0] = np.zeros((1,getActionSize()))
      # Reset số lần yếu liên tiếp
      per[6][0][0] = 0 
    elif per[5][0][1] > per[4][0][0] and per[4][0][1] == 1000:
      per[6][0][0] +=1 
      # Chuyển sang train
      per[5][0][0] = 0 
      per[2][0][0] = 0
      per[1][0] = np.zeros((1,getActionSize()))
      # Rest số trận thắng và số trận đấu 
      per[4][0][0] = 0
      per[4][0][1] = 0 

    if per[6][0][0] == 3 and per[11][0][0] < 200000 :
      per[5][0][0] = 4
      per[2][0][0] = 0
      per[4][0][0] = 0
      per[4][0][1] = 0 
      per[5][0][1] = 0 

    if per[11][0][0] == 200000:
      if per[4][0][0] > per[5][0][1] and per[4][0][1] == 1000:
        per[3][0] = np.copy(per[1][0]/np.max(per[1][0]))
        # Lưu lại kết quả thắng
        per[5][0][1] = 0 
        per[5][0][1] += (per[4][0][0])
        # Rest số trận thắng và số trận đấu 
        per[4][0][0] = 0
        per[4][0][1] = 0 
        # Chuyển sang train
        per[5][0][0] = 2 
        per[2][0][0] = 0
        per[1][0] = np.zeros((1,getActionSize()))
        # Reset số lần yếu liên tiếp
        per[6][0][0] = 0 

      elif per[5][0][1] > per[4][0][0] and per[4][0][1] == 1000:
        per[6][0][0] +=1 
        # Chuyển sang train
        per[5][0][0] = 2 
        per[2][0][0] = 0
        per[1][0] = np.zeros((1,getActionSize()))
        # Rest số trận thắng và số trận đấu 
        per[4][0][0] = 0
        per[4][0][1] = 0 
      
    # reset per[1][0] sau 10k trận
    if int(per[2][0][0]) == 10000:
      per[3][0] = np.copy(per[1][0]/np.max(per[1][0]))
      per[2][0][0] = 0
      per[5][0][0] = 1



    # Chế độ train 
    if int(per[2][0][0]) < 10000 and per[5][0][0] == 0  :
      actions = getValidActions(state)
      actions *= per[0][0]
      action = np.argmax(actions)
      if getReward(state) == 1 :
          per[1] += per[0][0]
      if getReward(state) == 0:
          per[0][0] = np.random.rand(getActionSize())

    # Chế độ test 
    elif int(per[2][0][0]) <1000  and per[5][0][0] == 1 : 
      list_action2 = getValidActions(state)
      action = np.argmax(list_action2*per[3][0])    
      if getReward(state) == 1:
        per[4][0][0]+=1
      if getReward(state) != -1:
        per[4][0][1]+=1  

    # Chế độ train policy yếu
    elif int(per[2][0][0]) < 10000 and per[5][0][0] == 2 and per[11][0][0] == 200000 :
      actions = getValidActions(state)
      actions *= per[7][0]
      action = np.argmax(actions)
      if getReward(state) == 1 :
          per[1] += per[0][0]
      if getReward(state) == 0:
          per[0][0] = np.random.rand(getActionSize())

    # chế độ test policy yếu
    elif int(per[2][0][0]) <1000 and  per[5][0][0] == 3 and per[11][0][0] == 200000:
      actions = getValidActions(state)
      actions *= per[7][0]
      action = np.argmax(actions)
      if getReward(state) == 1:
        per[4][0][0]+=1
      if getReward(state) != -1:
        per[4][0][1]+=1  


    # Báo chuyển sang chế độ lưu state và action
    if per[5][0][0] == 4 and per[11][0][0] < 200000:
      list_action2 = getValidActions(state)
      action = np.argmax(list_action2*per[3][0]) 


    # Lưu state và action
    if getReward(state) != -2 and per[11][0][0] < 200000 and per[5][0][0] == 4:
        per[11][0][0] += 1
        for i in range(getStateSize()):
          per[8][int(per[11][0][0])][i] += state[i]        
        per[9][int(per[11][0][0])][0] += int(action)
        per[10][int(per[11][0][0])][0] += int(getReward(state))

    # đếm số ván đấu 
    if getReward(state) != -1 :
        per[2][0][0] += 1
    return action,per

win, bias = numba_main_2(p_bias, 70000,perx,0)

In [7]:
perx

[array([[0.4560483 , 0.22748416, 0.97874192, 0.77073814, 0.64749204,
         0.4161435 , 0.20725905, 0.25595341, 0.59340325, 0.01235869,
         0.50382977, 0.80385259, 0.60171779, 0.74988241, 0.75459826]]),
 array([[194.51918596, 209.38823244, 204.41597904, 204.21790042,
         182.35539753, 183.28146548, 191.27772955, 183.77864744,
         179.53996226, 193.70928501, 185.839689  , 186.53204121,
         180.15634897, 172.35531819, 196.23366941]]),
 array([[1000.]]),
 array([[0.9606411 , 0.93565236, 0.9482516 , 1.        , 0.91289501,
         0.90392899, 0.90579019, 0.89525046, 0.90313639, 0.9123112 ,
         0.8897616 , 0.92687669, 0.92087409, 0.90951984, 0.89191974]]),
 array([[0., 0.]]),
 array([[  0., 606.]]),
 array([[2.]]),
 array([[0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0.

In [119]:
perx[1]/np.max(perx[1])

array([[0.93380679, 0.94004684, 0.97837602, 1.        , 0.90844661,
        0.89169024, 0.91621191, 0.92501138, 0.91669707, 0.92091342,
        0.92063013, 0.92974875, 0.92512236, 0.93810396, 0.91063767]])

In [120]:
perx

[array([[0.92881035, 0.04464409, 0.84400567, 0.73709625, 0.66078261,
         0.69203649, 0.59954252, 0.23249251, 0.73027685, 0.17044969,
         0.60943154, 0.34136479, 0.46969279, 0.82866415, 0.14255394]]),
 array([[3918.46330637, 3944.64797634, 4105.48582476, 4196.22492375,
         3812.04631576, 3741.73281641, 3844.63123573, 3881.55579313,
         3846.6670839 , 3864.35984753, 3863.171108  , 3901.43489208,
         3882.02149098, 3936.49520641, 3821.24049293]]),
 array([[20000.]]),
 array([[0.92367102, 0.93551514, 0.98833433, 1.        , 0.91506735,
         0.90667218, 0.93759879, 0.93465938, 0.92414673, 0.92823478,
         0.92911417, 0.91723864, 0.9343509 , 0.94062581, 0.90115702],
        [0.18712708, 0.71695997, 0.13739306, 0.11061017, 0.05453283,
         0.88021185, 0.37855952, 0.59711917, 0.95210496, 0.19998497,
         0.39171507, 0.37315239, 0.12671834, 0.54306523, 0.51353557],
        [0.90094587, 0.19775119, 0.76908433, 0.61422486, 0.70918202,
         0.48434937, 

In [76]:
import numpy as np
@njit
def find_property(state, reward):
    unique_states = np.unique(state, axis=0)
    properties = []
    for s in unique_states:
        mask = np.all(state == s, axis=1)
        avg_reward = np.mean(reward[mask])
        properties.append((s, avg_reward))
    return properties
find_property(perx[8],perx[10])

KeyboardInterrupt: 

In [75]:
perx[10]

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [74]:
perx[8]


array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 7.,  7.,  7., ...,  1., 12.,  0.],
       [ 2.,  6.,  7., ...,  1., 12.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [72]:
import numba
import numpy as np

@numba.njit
def find_important_feature(state, reward):
  n_features = state.shape[1]
  feature_count = np.zeros(n_features, dtype=np.int64)
  feature_value_count = [{} for _ in range(n_features)]
  
  for i in range(n_features):
    
    unique_values, counts = np.unique(state[:, i])
    print(counts)
    feature_count[i] = np.sum(counts)
    
    for value, count in zip(unique_values, counts):
      if value not in feature_value_count[i]:
        feature_value_count[i][value] = {"count": 0, "reward_count": 0}
        
      feature_value_count[i][value]["count"] = count
      feature_value_count[i][value]["reward_count"] = np.sum(reward[state[:, i] == value])
  
  important_feature = None
  important_feature_value = None
  lowest_percentage = 1
  
  for i in range(n_features):
    for value, count_data in feature_value_count[i].items():
      count = count_data["count"]
      reward_count = count_data["reward_count"]
      percentage = reward_count / count
      
      if percentage < lowest_percentage:
        lowest_percentage = percentage
        important_feature_value = value
  
  return important_feature, important_feature_value, lowest_percentage
find_important_feature(perx[8], perx[10])


TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function sum at 0x7fa54077d8b0>) found for signature:
 
 >>> sum(float64)
 
There are 2 candidate implementations:
      - Of which 2 did not match due to:
      Overload of function 'sum': File: numba/core/typing/npydecl.py: Line 378.
        With argument(s): '(float64)':
       No match.

During: resolving callee type: Function(<function sum at 0x7fa54077d8b0>)
During: typing of call at /var/folders/ds/4lcv95w11y7brm6dqhc04s240000gn/T/ipykernel_46954/2782407322.py (14)


File "../../../../var/folders/ds/4lcv95w11y7brm6dqhc04s240000gn/T/ipykernel_46954/2782407322.py", line 14:
<source missing, REPL/exec in use?>


In [59]:
import numpy as np
def find_important_feature(state, reward):
  for i in range(len(reward)):
      if reward[i] == -1:
          for j in range(i,len(reward)):
              if reward[j] != -1:
                  reward[i] = reward[j]
                  break
  
  n_features = state.shape[1]
  feature_count = np.zeros(n_features, dtype=int)
  feature_value_count = [{} for _ in range(n_features)]
  
  for i in range(n_features):    
    unique_values, counts = np.unique(state[:, i], return_counts=True)
    feature_count[i] = np.sum(counts)
    
    for value, count in zip(unique_values, counts):
      if value not in feature_value_count[i]:
        feature_value_count[i][value] = {"count": 0, "reward_count": 0}
        
      feature_value_count[i][value]["count"] = count
      feature_value_count[i][value]["reward_count"] = np.sum(reward[state[:, i] == value])
  
  important_feature = None
  important_feature_value = None
  lowest_percentage = 1
  
  for i in range(n_features):
    for value, count_data in feature_value_count[i].items():
      count = count_data["count"]
      reward_count = count_data["reward_count"]
      percentage = reward_count / count
      
      if percentage < lowest_percentage:
        lowest_percentage = percentage
        important_feature = "feature_{}".format(i)
        important_feature_value = value
  print(important_feature)
  print(important_feature_value)
  print(lowest_percentage)
  return important_feature, important_feature_value, lowest_percentage
find_important_feature(perx[8], perx[10])


TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function array>) found for signature:
 
 >>> array(array(float64, 2d, C))
 
There are 4 candidate implementations:
      - Of which 4 did not match due to:
      Overload in function '_OverloadWrapper._build.<locals>.ol_generated': File: numba/core/overload_glue.py: Line 131.
        With argument(s): '(array(float64, 2d, C))':
       Rejected as the implementation raised a specific error:
         TypingError: Failed in nopython mode pipeline (step: nopython frontend)
       No implementation of function Function(<intrinsic stub>) found for signature:
        
        >>> stub(array(float64, 2d, C))
        
       There are 2 candidate implementations:
         - Of which 2 did not match due to:
         Intrinsic in function 'stub': File: numba/core/overload_glue.py: Line 35.
           With argument(s): '(array(float64, 2d, C))':
          Rejected as the implementation raised a specific error:
            TypingError: array(float64, 2d, C) not allowed in a homogeneous sequence
         raised from /Users/trancatkhanh/opt/anaconda3/lib/python3.9/site-packages/numba/core/typing/npydecl.py:487
       
       During: resolving callee type: Function(<intrinsic stub>)
       During: typing of call at <string> (3)
       
       
       File "<string>", line 3:
       <source missing, REPL/exec in use?>

  raised from /Users/trancatkhanh/opt/anaconda3/lib/python3.9/site-packages/numba/core/typeinfer.py:1074

During: resolving callee type: Function(<built-in function array>)
During: typing of call at /var/folders/ds/4lcv95w11y7brm6dqhc04s240000gn/T/ipykernel_46954/55932719.py (8)


File "../../../../var/folders/ds/4lcv95w11y7brm6dqhc04s240000gn/T/ipykernel_46954/55932719.py", line 8:
<source missing, REPL/exec in use?>


# Find the most important value of index in the state that when it appear the policy dont work well


In [ ]:
def find_most_importane_feature(perx):
    import pandas as pd

    df = pd.DataFrame(perx[8])
    df['action'] = perx[9]
    df['reward'] = perx[10]
    for i in range(len(df)):
        if df['reward'][i] == -1:
            for j in range(i,len(df)):
                if df['reward'][j] != -1:
                    df['reward'][i] = df['reward'][j]
                    break
    df = df[df['reward'] != -1]

    import pandas as pd
    from sklearn.ensemble import RandomForestClassifier

    # Load the state-action dataset

    # Split the data into features (state properties) and target (outcome)
    features = df.drop("reward", axis=1)
    target = df["reward"]

    # Train a Random Forest Classifier on the data
    clf = RandomForestClassifier()
    clf.fit(features, target)

    # Get the feature importances
    importances = clf.feature_importances_

    # Find the property (x) of the state that is most important for the policy's performance
    x = features.columns[importances.argmax()]
    # Plot the top  feature importances 
    import matplotlib.pyplot as plt
    import numpy as np
    indices = np.argsort(importances)[::-1]
    plt.figure(figsize=(10, 5))
    plt.title("Feature importances")
    plt.bar(range(features.shape[1]), importances[indices], color="r", align="center")
    plt.xticks(range(features.shape[1]), features.columns[indices], rotation=90)
    plt.xlim([-1, features.shape[1]])
    plt.show()
    most_imp_feature = None
    lowest_percentage = 100
    print('feature importances',x)
    for i in df[x].unique():
        current_percentage = df[df[x] == i]['reward'].value_counts()[1]/df[df[x] == i]['reward'].value_counts().sum()
        if current_percentage < lowest_percentage:
            most_imp_feature = i
            lowest_percentage = current_percentage

    print("The value of the most important feature with the lowest percentage of value 1 in reward is:", most_imp_feature)#  all the below code in one function    
    return most_imp_feature
